// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

package company

import (
	stdcontext "context"
	"fmt"
	"net/http"

	issues_model "gitea.dev/models/issues"
	repo_model "gitea.dev/models/repo"
	"gitea.dev/modules/setting"
	"gitea.dev/services/context"
)

// verifyDeployRequestPR confirms pr is actually a Deploy Request PR on the
// currently configured central deploy repo — same-repo PR, deploy/-shaped
// branch, and the repo it's really on matches [company] CENTRAL_DEPLOY_REPO
// — and returns the department repo (owner/name) it came from. Shared by
// SetDeployRequestPageData (decides whether to show the button) and
// TriggerDeployRequestAIReview (re-verifies before actually acting on a
// click) so both apply exactly the same rule.
// allowClosed is for the pages that still have something to say about a
// closed request — its outcome, who asked — as opposed to the actions that
// need its branch, which cleanup has deleted by then.
func verifyDeployRequestPR(ctx stdcontext.Context, pr *issues_model.PullRequest, allowClosed bool) (deptOwner, deptName string, ok bool) {
	if pr.BaseRepoID != pr.HeadRepoID {
		return "", "", false
	}
	deptOwner, deptName, _, ok = parseDeployBranchName(pr.HeadBranch)
	if !ok {
		return "", "", false
	}
	if err := pr.LoadIssue(ctx); err != nil {
		return "", "", false
	}
	if pr.Issue.IsClosed && !allowClosed {
		// closed means deployBranchCleanupNotifier (company/deploy_notifier.go)
		// already deleted this branch — there's no diff left to review either way
		return "", "", false
	}

	centralOwner, centralName, err := centralDeployOwnerName()
	if err != nil {
		return "", "", false
	}
	if err := pr.LoadBaseRepo(ctx); err != nil {
		return "", "", false
	}
	if pr.BaseRepo.OwnerName != centralOwner || pr.BaseRepo.Name != centralName {
		return "", "", false
	}
	return deptOwner, deptName, true
}

// SetDeployRequestPageData runs ahead of Gitea's native repo.ViewIssue
// on every /{owner}/{repo}/pulls/{index} view (routers/web/web.go) — cheap
// on the vast majority of PRs it'll see (bails on the first check that
// fails), and only ever adds data for the template to conditionally render
// something from; never blocks or alters the native page otherwise.
//
// Deliberately admin-only, and on the platform AI (company/platform_ai.go),
// not the viewing admin's own. Whether it is set up yet changes what shows,
// not whether anything does — until it is, the page points at 관리 → AI
// instead of the review button silently not being there.
func SetDeployRequestPageData(ctx *context.Context) {
	if ctx.Doer == nil || !ctx.Doer.IsAdmin || ctx.Repo.Repository == nil {
		return
	}
	index := ctx.PathParamInt64("index")
	pr, err := issues_model.GetPullRequestByIndex(ctx, ctx.Repo.Repository.ID, index)
	if err != nil {
		return // not a PR, or doesn't exist — repo.ViewIssue itself will 404 as usual
	}
	if isCentralDeployRepo(ctx.Repo.Repository) {
		// Every pull request on the central repository is approved the same
		// way, including one opened by hand: the button says what it does
		// (routers/web/repo/pull_merge_form.go).
		ctx.Data["CompanyMergeLabel"] = ctx.Locale.Tr("company.review.approve_deploy")
	}
	deptOwner, deptName, ok := verifyDeployRequestPR(ctx, pr, true)
	if !ok {
		return
	}
	setDeployReviewData(ctx, pr, deptOwner, deptName) // the sidebar built for this decision — company/deploy_review.go
	if pr.Issue.IsClosed {
		return // nothing left to review
	}
	if PlatformAIUnavailableReason(ctx) != "" {
		ctx.Data["ShowDeployAIReviewSetup"] = true
		ctx.Data["DeployAIReviewSetupURL"] = setting.AppSubURL + "/-/admin/company-ai"
		return
	}
	ctx.Data["ShowDeployAIReview"] = true
	ctx.Data["DeployAIReviewURL"] = fmt.Sprintf("%s/company/deploy-request/%d/ai-review", setting.AppSubURL, pr.ID)
	ctx.Data["DeployAIReviewStatus"] = codeReviewStatusFor(pr.ID)
	// While the AI auto-deploy is deciding this request, a code review waits
	// for it rather than running alongside; forcing one stops the auto-deploy.
	if s := autoApproveStatusFor(pr.ID); s.Phase == autoApprovePhaseReviewing || s.Phase == autoApprovePhaseWaiting {
		ctx.Data["DeployAIReviewPending"] = s
	}
}

// TriggerDeployRequestAIReview posts a fresh AI review comment on-demand,
// posted as whoever clicked the button and generated by the platform AI — see
// generateAIReview (company/deploy.go) for the shared prompt/diff logic.
// Re-verifies everything SetDeployRequestPageData already checked
// before showing the button: a hidden button is not the same as an
// unauthorized action, and this is reachable directly by URL regardless of
// what any page happened to render. Mounted at
// /company/deploy-request/{id}/ai-review (company/routes.go), keyed by
// pull_request.id the same way CancelDeployRequest is.
func TriggerDeployRequestAIReview(ctx *context.Context) {
	if !ctx.Doer.IsAdmin {
		ctx.NotFound(nil)
		return
	}

	id := ctx.PathParamInt64("id")
	pr, err := issues_model.GetPullRequestByID(ctx, id)
	if err != nil {
		ctx.NotFound(err)
		return
	}
	deptOwner, deptName, ok := verifyDeployRequestPR(ctx, pr, false) // loads pr.Issue itself, see there
	if !ok {
		ctx.NotFound(nil)
		return
	}
	if reason := PlatformAIUnavailableReason(ctx); reason != "" {
		ctx.HTTPError(http.StatusBadRequest, ctx.Locale.TrString(reason))
		return
	}

	central := pr.BaseRepo
	deptRepo, err := repo_model.GetRepositoryByOwnerAndName(ctx, deptOwner, deptName)
	if err != nil {
		// department repo renamed/deleted since — still worth reviewing, just with a plainer label
		deptRepo = &repo_model.Repository{OwnerName: deptOwner, Name: deptName}
	}

	if s := autoApproveStatusFor(pr.ID); s.Phase == autoApprovePhaseReviewing || s.Phase == autoApprovePhaseWaiting {
		if !ctx.FormBool("force") {
			ctx.Flash.Info(ctx.Locale.TrString("company.pulls.ai_review_pending_flash"))
			ctx.Redirect(fmt.Sprintf("%s/pulls/%d", central.Link(), pr.Issue.Index))
			return
		}
		// Forced: the person asking to read it first is deciding it, not the auto-deploy.
		stopAutoApprove(pr.ID, ctx.Doer.Name)
	}

	// In the background, so the page comes back at once and shows the review
	// under way (company/ai_review_progress.go) instead of hanging on the click.
	if run, fresh := startCodeReview(pr.ID, ctx.Doer.Name); fresh {
		go postAIReviewComment(run, pr.ID, central, ctx.Doer, pr.Issue, pr.HeadBranch, deptRepo.FullName(), pr.Issue.Title, "요청: @"+ctx.Doer.Name)
	}
	ctx.Redirect(fmt.Sprintf("%s/pulls/%d", central.Link(), pr.Issue.Index))
}
